config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  devise_for :users

  resources :books, only: [:show, :index, :create, :edit ,:destroy]
  resources :users, only: [:show, :index, :edit, :create] 

  get "/homes/about" => "homes#about", as: "about"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  
  def new
    @book = Book.new  
  end
  
  def create
    book = Book.new(book_params)
    book.save
    redirect_to '/books'
  end
  
  private
  
  def book_params
    params.require(:book).permit(:title, :body)
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_one_attached :profile_image


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    users_path
  end
  
  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
    devise_parameter_sanitizer.permit(:update, keys: [:name,:profile_image,:introduction])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def new
   @book = Book.new
  end

  def index
   @books = Book.all
   @book = Book.new
  end

  def create
    if @book.save
      flash[:notice] = "Book was successfully updated."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.new
  end

  def index
    @users = User.all
    @books = Book.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def create
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)  
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)  
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>

app/views/books/index.html.erb
<div class="container">
 <div class="row">
   
    <div class= "col-md-3">
      <%= render 'users/info', users: @users %>
   </div>
   
  <div class= "col-md-8 offset-md-1">

<h1>Books#index</h1>
<p>Find me in app/views/books/index.html.erb</p>

<h1>Books</h1>

<table class="table table-hover table-inverse">
 
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  
  <tbody>
    <tr>
      <% @books.each do |book| %>
      <th></th>
      <th><span><%= book.title %></span></th>
      <th><span><%= book.body %></span></th>
      <% end %>
    </tr>
  </tbody>
  
</table>

  </div>
 </div>
</div>

app/views/books/show.html.erb
<h1>Books#show</h1>
<p>Find me in app/views/books/show.html.erb</p>

<h1>Book detail</h1>

app/views/homes/about.html.erb
<h1 class="row justify-content-center mt-3 mb-5">Welcome to <i class="fa-solid fa-book"></i> <strong>Bookers!</strpng> </h1>

app/views/homes/top.html.erb
<div class=" col-5 mx-auto">  
 
 <h1>welcome to <i class="fa-solid fa-book"></i> <strong>Bookers</strong> !!</h1>
 <h5>In <i class="fa-solid fa-book"></i> <strong>Bookers</strong>,</h5>

 <p>you can share and exchange your opinions , inpressions , and emotions</p>
 <p>about various books!</p>

</div>

<div class="btn-wrapper col-4 mx-auto">      
 <p class="row justify-content-center"><%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-block btn-sm"  %></p>
 <p class="row justify-content-center"><%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-block btn-sm"  %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://kit.fontawesome.com/7cae1128b7.js" crossorigin="anonymous"></script>
  </head>

  <body>
    
   <nav class="navbar navbar-expand-lg navbar-dark bg-dark py-10 px-20 ">
    <div class="container">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
       <span class="navbar-toggler-icon"></span>
      </button>
      
      <a href="/">
       <h5 class="link">Bookers</h5>
      </a> 
      
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav ml-auto">
     <% if user_signed_in? %>
       <li class="nav-item">
        <%= link_to users_path(current_user.id), class: 'link' do %>
         <i class="fa-duotone fa-house-chimney"></i>Home
        <% end %>
       </li>
       <li class="nav-item">
        <%= link_to user_path(current_user.id), class:'link' do %>
         <i class="fa-duotone fa-users"></i>Users
        <% end %>
       </li>
       <li class="nav-item">
        <%= link_to books_path(current_user.id), class:'link' do %>
         <i class="fa-solid fa-book-open"></i>Books
        <% end %>
       </li>
       <li class="nav-item">
        <%= link_to destroy_user_session_path, method: :delete, class:'link' do %>
         <i class="fa-solid fa-right-from-bracket"></i>Log out
        <% end %>
       </li>
     <% else %>
       <li class="nav-item">
        <%= link_to root_path, class:'link' do %>
         <i class="fa-duotone fa-house-chimney"></i>Home
        <% end %>
       </li>
       <li class="nav-item">
        <%= link_to about_path, class:'link' do %>
         <i class="fa-solid fa-link"></i>About
        <% end %>
       </li>
       <li class="nav-item">
        <%= link_to new_user_registration_path, class:'link' do %>
         <i class="fa-solid fa-user-plus"></i>Sign up
        <% end %>
       </li>
       <li class="nav-item">
        <%= link_to new_user_session_path, class:'link' do %>
         <i class="fa-solid fa-right-to-bracket"></i>Log in
        <% end %>
       </li>
     <% end %>
     </ul>
    </div>
    </div>
   </nav>

   <%= yield %>
   
   <footer class="row justify-content-center">
     CopyRight Infratop.inc
   </footer>
   
  </body>



</html>

app/views/users/_info.html.erb
<h2>User info</h2>


  <p class="border-bottom">
    <%= image_tag 'no_image', size:"100×100" %>
  </p>

  <p class="border-bottom"><strong>name  <%= current_user.name %></strong></p>

  <p><strong>introduction  <%= current_user.introduction %></strong></p>

  <%= link_to edit_user_path(current_user.id) , class:"btn btn-outline-secondary col-12" do %>
    <i class="fa-solid fa-user-gear"></i>
  <% end %>



<h2>New Book</h2>

<%= form_with model: @book , url:'/books' , method: :post do |f| %>

  <p>Title</p>
  <%= f.text_field :title %>

  <p>Opinion</p>
  <%= f.text_area :body %>

  <p>
   <%= f.submit 'Create Book' ,class:"btn btn-success" %>
  </p>
  
<% end %>

app/views/users/edit.html.erb
<div class=" col-5 mx-auto">

<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

<%= form_with model: @user , local: true , url: edit_user_registration_path do |f| %>

  <h4>Name</h4>
  <%= f.text_field :name %>

  <h4>Image</h4>
  <%= f.file_field :profile_image, accept: "image/*" %>

  <h4>Introduction</h4>
  <%= f.text_area :introduction %>

  <p>
  <button type="submit" class="btn btn-secondary">
    Update User
  </button>
  </p>
  <%# 反応しない↑ %>

<% end %>

</div>

app/views/users/index.html.erb
<div class="container">
 <div class="row">
  <div class= "col-md-3">
    <%= render 'info', users: @users %>
  </div>
  
  <div class= "col-md-8 offset-md-1">
    <h1>Users#index</h1>
    <p>Find me in app/views/users/index.html.erb</p>

<h1>Books</h1>

<table class="table table-hover table-inverse">
 
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  
  <tbody>
    <tr>
      
      <th></th>
      <th><span></span></th>
      <th><span></span></th>
      
    </tr>
  </tbody>
  
</table>

  </div>
 </div>
</div>

app/views/users/show.html.erb
<div class="container">
 <div class="row">
   
  <div class= "col-md-3">
   <%= render 'info', users: @users %>
  </div>
  
   <div class= "col-md-8 offset-md-1">
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

    <h2>Users</h2>
      <table class="table table-hover table-inverse">
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
      </table>

   </div>
  
 </div>
</div>